graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql:  mapping: /graphiql  endpoint: /graphql
  enabled: true
  pageTitle: GraphQL
  cdn:    enabled: false
    version: 0.11.11